[workspace]
members = [
    "bin/helix-grimoire-api",
    "helix-grimoire-domain",
]

##DEFAULT RUNNING BIN
default-members=["bin/helix-grimoire-api"]


##__FIX FOR ARM COMPILATION SINCE RUST 1.38
[profile.release]
codegen-units = 1